sudo: required
services: 
    - docker

before_install:
    - docker build -t mateusz95wat/docker-react -f Dockerfile.dev .
    
script:
    - docker run mateusz95wat/docker-react npm run test -- --coverage